version: '3.8'

services:
  catalog-service:
    image: soekopaacykel/catalogservice:latest
    container_name: catalogservice
    environment:
      - ImagePath=/srv/images
    ports:
      - "5001:8080"
    networks:
      - mitnet
    volumes:
      - catalog-images:/srv/images


volumes:
  catalog-images:
    external: false
  
networks:
  default:
    driver: bridge
    name: mitnet